bal/courseapp/bal/urls.py
from django.urls import path
from . import views #response için görüntü dosyasına yönlendirdik






urlpatterns = [
    path('', views.anasayfa),
    path('hakkında', views.hakkında, name='hakkında'),
    path('shop', views.shop, name='shop'),
    path('contact', views.contact, name='contact'),
    path('urun_ekle', views.urun_ekle, name='urun_ekle'),
    path('urun_detay/<slug:slug>/<int:id>', views.urun_detay, name='urun_detay'),

]




# urlpatterns = [
#     path('', views.home),
#     path('borc', views.borc, name='borc'),
#     path('sonuc/<int:id>', views.sonuc, name='sonuc'),
#     path('gıda', views.gıda, name='gıda'),
#     path('aileharcama', views.aileharcama, name='aileharcama'),
#     path('kartlar', views.kartlar, name='kartlar'),
#     path('analiz', views.analiz, name='analiz'),
#     path('silgıdaharcama', views.silgıdaharcama, name='silgıdaharcama'),
    
#     path('silsercanharcama', views.silsercanharcama, name='silsercanharcama'),
#     path('silmehmetharcama', views.silmehmetharcama, name='silmehmetharcama'),
#     path('silerenharcama', views.silerenharcama, name='silerenharcama'),

#     path('sercanharcama', views.sercanharcama, name='sercanharcama'),
#     path('mehmetharcama', views.mehmetharcama, name='mehmetharcama'),
#     path('erenharcama', views.erenharcama, name='erenharcama'),



#     #______________SİL_______________________
#     path('kart_sil/<int:id>', views.kart_sil, name='kart_sil'),
#     path('sil/<int:id>', views.sil, name='sil'),
#     path('gıda_sil/<int:id>', views.gıda_sil, name='gıda_sil'),


#     #_____________________EKLE________________
#     path('ekle', views.ekle, name='ekle'),
#     path('kart_ekle', views.kart_ekle, name='kart_ekle'),
#     path('eklegıda', views.eklegıda, name='eklegıda'),
#     path('gıdaisimekle', views.gıdaisimekle, name='gıdaisimekle')

    




    # path('iletişim', views.kurslar),
    # path('search', views.search, name='search'),#arama sayfası burası
    # path('post', views.post, name='post'),#post
    # path('post2', views.post2, name='post2'),#post etme ve girilen verileri kontrol etme
    # path('ürün_detay', views.ürün_detay, name='ürün_detay'),
    # path('güncelle/<int:idurls>', views.güncelle, name='güncelle'),
    # path('sil/<int:idurls>', views.sil, name='sil'),
    # path('yükle', views.yükle, name='resim_yükle'),
    # path('index', views.index),
    # path('index/<int:kategori>', views.kategori),
    # path('veritabanı', views.veritabanı),
    
    # path('anasayfa', views.anasayfa),
    # path('<int:kategori>',views.dinamik),#burda ketegori değişkenimizi oluşturduk.Eğer str türünde veri
    # #alırsa views.dinamik çalışır
    # #not:yukarıdan aşağıya okuma yaptığı için üstte şartı karşılayan bir path varsa onu görür 
    # #aşağıdakileri görmez.
    # path('<str:kategori>',views.dinamikstr),
# ]
    

bal/courseapp/courseapp/urls.py
from django.conf import settings#media yüklemesi için 
from django.conf.urls.static import static#media yüklemesi için
from django.contrib import admin
from django.urls import path, include #burada dahil etme(include) ktüphanesini ekledik
import statistics
from django.conf import settings

urlpatterns = [
    path('', include('bal.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
+ statistics(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bal/courseapp/bal/models.py
from django.db import models
import datetime
from django.utils.text import slugify #slugify (java-kursu) import ettik


class Urun(models.Model):
    ad = models.CharField(max_length=100)
    aciklama = models.TextField()
    fiyat = models.DecimalField(max_digits=10, decimal_places=2)
    resim = models.ImageField(upload_to='bal_resmi/')

    kayit_tarihi = models.DateField(auto_now_add=True)
    isActive=models.BooleanField()
    slug=models.SlugField(default="", null=False, blank=True)# boş geçilebilir null=False ile

    def __str__(self):
        return self.ad

    def save(self,*args, **kwargs):
        self.slug=slugify(self.ad) #slug işlemleri için sonradan oluşturuldu isimden slug yapıyor
        super().save(args,kwargs)

bal/courseapp/bal/forms.py
from django import forms
from .models import Urun

class UrunForm(forms.ModelForm):
    class Meta:
        model = Urun
        fields = ['ad', 'aciklama', 'fiyat', 'resim', 'isActive']

bal/courseapp/bal/views.py
import json
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpRequest, HttpResponse
from bal.forms import UrunForm    #hesap klasörünün altındakı forms.py kategoriyi import ettik
from .models import Urun #burada veri tabnını import ettik
import random #rastgele sayı üretmek için
import os
from django.contrib.auth.decorators import login_required #loginmi kontrolleri için


from django.contrib import messages
import datetime
# Create your views here.





def anasayfa(request):
    return render(request, 'bal/anasayfa.html')

def contact(request):
    return render(request, 'bal/contact.html')

def hakkında(request):
    return render(request, 'bal/hakkında.html')

def shop(request):
    entries = Urun.objects.all()
    return render(request, 'bal/shop.html',{'entries': entries})



def urun_ekle(request):
    if request.method == 'POST':
        form = UrunForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('urun_ekle')  # Yeniden formu temiz bir şekilde göstermek için aynı sayfaya yönlendiriyoruz
    else:
        form = UrunForm()
    return render(request, 'bal/urun_ekle.html', {'form': form})


def urun_detay(request, id, slug): 
    form = get_object_or_404(Urun, id=id)#id bilgisini dışardan gelen
     #idurlsye eşitledik
    return render(request, 'bal/urun_detay.html', {'form': form})



# def home(request):
#     toplam_borc = Ödeme.objects.aggregate(toplam_borc=Sum('miktar'))
#     entries = Ödeme.objects.all()



#     return render(request, 'hesap/hesap.html',{'entries': entries,
#                                                'toplam_borc': toplam_borc, })

# def kartlar(request):
#     entries = Kartlar.objects.all()
#     return render(request, 'hesap/kartlar.html',{'entries': entries})

# def borc(request):
#     toplam_borc = Ödeme.objects.aggregate(toplam_borc=Sum('miktar'))
#     entries = Ödeme.objects.all()


#     return render(request, 'hesap/borc.html',{'entries': entries,
#                                                'toplam_borc': toplam_borc})

# def sonuc(request, id): 
#     data=Kartlar.objects.get(pk=id) #id nosuna göre sorgulama yapar.
#     print(data.isim)
#     if data.isim=="Ziraat":
#         print("gerekli işlemler için seleniuma yönlendirliyorsunuz")
#         ziraat_giris()
#     if data.isim=="Akbank":
#         print("gerekli işlemler için seleniuma yönlendirliyorsunuz")
#         akbank_giris()    
#     if data.isim=="Halkbank":
#         print("gerekli işlemler için seleniuma yönlendirliyorsunuz")
#         halkbank_giris()
#     if data.isim=="Enpara":
#         print("gerekli işlemler için seleniuma yönlendirliyorsunuz")
#         enpara_giris()          

#     return render(request, 'hesap/sonuc.html')

# def gıda(request):
#     harcamalar = gıda.objects.all()
#     return render(request, 'hesap/gıda.html', {'harcamalar': harcamalar})

# def aileharcama(request):
#     toplam_gida_harcamasi = GidaHarcamasi.objects.aggregate(toplam_gida_harcamasi=Sum('tutar'))
#     entries = GidaHarcamasi.objects.all()
#     return render(request, 'hesap/aileharcama.html',{'entries': entries,
#                                                'toplam_gida_harcamasi': toplam_gida_harcamasi,
#                                                })

# def analiz(request):#burada toplam tutarların analizi var

#     entries = Gıdaisimleri.objects.all()

#     if request.method=='POST':
#         ayy=request.POST['ay']
#         yıll=request.POST['yıl']
#         isim=request.POST['gıdaismi']
#         print(f"{ayy}------> {yıll}------->{isim}")
#         toplam = GidaHarcamasi.objects.filter(gida_adi=isim, kayit_tarihi__year=yıll, kayit_tarihi__month=ayy).aggregate(toplam_tutar=Sum('tutar'))
#         print(toplam)
#         return render(request, 'hesap/analiz.html', {'toplam': toplam})#post requesti gelince yönlendirme(anasayfaya yönlendirdi)
#     return render(request, 'hesap/analiz.html',{'entries': entries})







#  #__________________EKLE________________________



# def ekle(request):
#      if request.method == 'POST':
#          form = KategoriForm(request.POST)
#          if form.is_valid():
#              # Form doğrulandı, verileri işle
#              form.save()
#              # Başka bir yere yönlendir
#              return redirect('/')#post requesti gelince yönlendirme(anasayfaya yönlendirdi)
         
#          print(form)
#      else:
#          form = KategoriForm()
#      return render(request, 'hesap/ekle.html', {'form': form})

# def kart_ekle(request):
#      if request.method == 'POST':
#          form = KartForm(request.POST)
#          if form.is_valid():
#              # Form doğrulandı, verileri işle
#              form.save()
#              # Başka bir yere yönlendir
#              return redirect('/kartlar')#post requesti gelince yönlendirme(anasayfaya yönlendirdi)
         
#          print(form)
#      else:
#          form = KartForm()
#      return render(request, 'hesap/kart_ekle.html', {'form': form})

# def eklegıda(request):
#      entries = Gıdaisimleri.objects.all()  
#      if request.method == 'POST':
#          form = GidaHarcamasiForm(request.POST)
#          if form.is_valid():
#              # Form doğrulandı, verileri işle
#              form.save()
#              # Başka bir yere yönlendir
#              return redirect('/aileharcama')#post requesti gelince yönlendirme(anasayfaya yönlendirdi)
         
#          print(form)
#      else:
#          form = GidaHarcamasiForm()
#      return render(request, 'hesap/eklegıda.html', {'form': form,
#                                                     'entries': entries})

# def gıdaisimekle(request):
#     entries = Gıdaisimleri.objects.all()
    
#     if request.method == 'POST':
#         gida_adi = request.POST['gıdaname']
        
#         if Gıdaisimleri.objects.filter(gida_adi=gida_adi).exists():
#             messages.warning(request, 'Bu gıda ismi zaten mevcut.')
#         else:
#             kurslar = Gıdaisimleri(gida_adi=gida_adi)
#             kurslar.save()
#             return redirect('/gıdaisimekle')
    
#     return render(request, 'hesap/gıdaisimekle.html', {'entries': entries})
#     #get requesti gelince yönlendirme





# #__________________SİL________________________
# def kart_sil(request, id): 
#      ödeme = get_object_or_404(Kartlar, id=id)#id bilgisini dışardan gelen
#      #idurlsye eşitledik
#      if request.method == 'POST':
#              ödeme.delete()# Başarılı bir şekilde silme formu yapıldığında yapılacak işlemler
#              return redirect("/kartlar") #anasayfaya yönlendirdi       
            
#      else:
#          form = ödeme
#      return render(request, 'hesap/kart_sil.html', {'form': form})


# def sil(request, id): 
#      ödeme = get_object_or_404(Ödeme, id=id)#id bilgisini dışardan gelen
#      #idurlsye eşitledik
#      if request.method == 'POST':
#              ödeme.delete()# Başarılı bir şekilde silme formu yapıldığında yapılacak işlemler
#              return redirect("/") #anasayfaya yönlendirdi       
            
#      else:
#          form = ödeme
#      return render(request, 'hesap/sil.html', {'form': form})

# def gıda_sil(request, id): 
#      gıdaisim = get_object_or_404(Gıdaisimleri, id=id)#id bilgisini dışardan gelen
#      #idurlsye eşitledik
#      if request.method == 'POST':
#              gıdaisim.delete()# Başarılı bir şekilde silme formu yapıldığında yapılacak işlemler
#              return redirect("/gıdaisimekle") #anasayfaya yönlendirdi       
            
#      else:
#          form = gıdaisim
#      return render(request, 'hesap/gıda_sil.html', {'form': form})

# def silgıdaharcama(request):
#    if request.method=='POST':
#         id_no=request.POST['id_no']
#         ödeme = get_object_or_404(GidaHarcamasi, id=id_no)
#         ödeme.delete()# Başarılı bir şekilde silme formu yapıldığında yapılacak işlemler
#         return redirect("/silgıdaharcama") #anasayfaya yönlendirdi  

#    else:
#         entries = GidaHarcamasi.objects.all()
#         return render(request, 'hesap/silgıdaharcama.html',{'entries': entries})

# def silsercanharcama(request):
#    if request.method=='POST':
#         id_no=request.POST['id_no']
#         ödeme = get_object_or_404(Sercanharcama, id=id_no)
#         ödeme.delete()# Başarılı bir şekilde silme formu yapıldığında yapılacak işlemler
#         return redirect("/silsercanharcama") #anasayfaya yönlendirdi  

#    else:
#         entries = Sercanharcama.objects.all()
#         return render(request, 'hesap/silsercanharcama.html',{'entries': entries})

# def silmehmetharcama(request):
#    if request.method=='POST':
#         id_no=request.POST['id_no']
#         ödeme = get_object_or_404(Mehmetharcama, id=id_no)
#         ödeme.delete()# Başarılı bir şekilde silme formu yapıldığında yapılacak işlemler
#         return redirect("/silmehmetharcama") #anasayfaya yönlendirdi  

#    else:
#         entries = Mehmetharcama.objects.all()
#         return render(request, 'hesap/silmehmetharcama.html',{'entries': entries})

# def silerenharcama(request):
#    if request.method=='POST':
#         id_no=request.POST['id_no']
#         ödeme = get_object_or_404(Erenharcama, id=id_no)
#         ödeme.delete()# Başarılı bir şekilde silme formu yapıldığında yapılacak işlemler
#         return redirect("/silerenharcama") #anasayfaya yönlendirdi  

#    else:
#         entries = Erenharcama.objects.all()
#         return render(request, 'hesap/silerenharcama.html',{'entries': entries})






































# def veritabanı(request):

#     kurslar=Book.objects.all()
#     return render(request,'pages/veritabanı.html',{"kurs":kurslar})

# def index(request):
#     entries = Kategori.objects.all()
#     context = {'entries': entries}

#     return render(request, 'pages/index.html', context)

# def search(request):

bal/courseapp/bal/templates/bal/about - Kopya.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Zay Shop - About Page</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="{% static 'bal/img/apple-icon.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'bal/img/favicon.ico' %}">

   
    <link rel="stylesheet" href="{% static 'bal/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bal/css/templatemo.css' %}">
    <link rel="stylesheet" href="{% static 'bal/css/custom.css' %}">
 
    <!-- Load fonts style after rendering the layout styles -->
   
    <link rel="stylesheet" href="{% static 'bal/css/fontawesome.min.css' %}">
<!--
    
TemplateMo 559 Zay Shop

https://templatemo.com/tm-559-zay-shop

-->
</head>

<body>



 




 <!-- Start Banner -->
    <section class="bg-success py-5">
        <div class="container">
            <div class="row align-items-center py-5">
                <div class="col-md-8 text-white">
                    <h1>Anasayfa</h1>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    </p>
                </div>
                <div class="col-md-4">
                    <img src="{% static 'bal/img/about-hero.svg' %}" alt="About Hero">
                   
                </div>
            </div>
        </div>
    </section>
    <!-- Close Banner -->


    <!-- Start Section -->
    <section class="container py-5">
        <div class="row text-center pt-5 pb-3">
            <div class="col-lg-6 m-auto">
                <h1 class="h1">Our Services</h1>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    Lorem ipsum dolor sit amet.
                </p>
            </div>
        </div>
        <div class="row">

            <div class="col-md-6 col-lg-3 pb-5">
                <div class="h-100 py-5 services-icon-wap shadow">
                    <div class="h1 text-success text-center"><i class="fa fa-truck fa-lg"></i></div>
                    <h2 class="h5 mt-4 text-center">Delivery Services</h2>
                </div>
            </div>

            <div class="col-md-6 col-lg-3 pb-5">
                <div class="h-100 py-5 services-icon-wap shadow">
                    <div class="h1 text-success text-center"><i class="fas fa-exchange-alt"></i></div>
                    <h2 class="h5 mt-4 text-center">Shipping & Return</h2>
                </div>
            </div>

            <div class="col-md-6 col-lg-3 pb-5">
                <div class="h-100 py-5 services-icon-wap shadow">
                    <div class="h1 text-success text-center"><i class="fa fa-percent"></i></div>
                    <h2 class="h5 mt-4 text-center">Promotion</h2>
                </div>
            </div>

            <div class="col-md-6 col-lg-3 pb-5">
                <div class="h-100 py-5 services-icon-wap shadow">
                    <div class="h1 text-success text-center"><i class="fa fa-user"></i></div>
                    <h2 class="h5 mt-4 text-center">24 Hours Service</h2>
                </div>
            </div>
        </div>
    </section>
    <!-- End Section -->



    <!-- Start Brands -->
    <section class="bg-light py-5">
        <div class="container my-4">
            <div class="row text-center py-3">
                <div class="col-lg-6 m-auto">
                    <h1 class="h1">Our Brands</h1>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        Lorem ipsum dolor sit amet.
                    </p>
                </div>
                <div class="col-lg-9 m-auto tempaltemo-carousel">
                    <div class="row d-flex flex-row">
                        <!--Controls-->
                        <div class="col-1 align-self-center">
                            <a class="h1" href="#templatemo-slide-brand" role="button" data-bs-slide="prev">
                                <i class="text-light fas fa-chevron-left"></i>
                            </a>
                        </div>
                        <!--End Controls-->

                        <!--Carousel Wrapper-->
                        <div class="col">
                            <div class="carousel slide carousel-multi-item pt-2 pt-md-0" id="templatemo-slide-brand" data-bs-ride="carousel">
                                <!--Slides-->
                                <div class="carousel-inner product-links-wap" role="listbox">

                                    <!--First slide-->
                                    <div class="carousel-item active">
                                        <div class="row">
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="assets/img/brand_01.png" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="assets/img/brand_02.png" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="assets/img/brand_03.png" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="assets/img/brand_04.png" alt="Brand Logo"></a>
                                            </div>
                                        </div>
                                    </div>
                                    <!--End First slide-->

                                    <!--Second slide-->
                                    <div class="carousel-item">
                                        <div class="row">
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="assets/img/brand_01.png" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="assets/img/brand_02.png" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="assets/img/brand_03.png" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="assets/img/brand_04.png" alt="Brand Logo"></a>
                                            </div>
                                        </div>
                                    </div>
                                    <!--End Second slide-->

                                    <!--Third slide-->
                                    <div class="carousel-item">
                                        <div class="row">
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="assets/img/brand_01.png" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="assets/img/brand_02.png" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="assets/img/brand_03.png" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="assets/img/brand_04.png" alt="Brand Logo"></a>
                                            </div>
                                        </div>
                                    </div>
                                    <!--End Third slide-->

                                </div>
                                <!--End Slides-->
                            </div>
                        </div>
                        <!--End Carousel Wrapper-->

                        <!--Controls-->
                        <div class="col-1 align-self-center">
                            <a class="h1" href="#templatemo-slide-brand" role="button" data-bs-slide="next">
                                <i class="text-light fas fa-chevron-right"></i>
                            </a>
                        </div>
                        <!--End Controls-->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--End Brands-->

bal/courseapp/bal/templates/bal/urun_detay.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>ürün detay sayfası</h1>
    <h2>Ürün Adı: {{form}}</h2>
</body>
</html>

bal/courseapp/bal/templates/bal/urun_ekle.html
{% extends 'ana.html' %}
{% load static %}
{% block css_files %}

    <link rel="apple-touch-icon" href="{% static 'bal/img/apple-icon.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'bal/img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'bal/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bal/css/templatemo.css' %}">
    <link rel="stylesheet" href="{% static 'bal/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'bal/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap' %}">
    {% endblock css_files %}
    
{% block js_alani %}
    <script src="{% static 'bal/js/jquery-1.11.0.min.js' %}"></script>
    <script src="{% static 'bal/js/jquery-migrate-1.2.1.min.js' %}"></script>
    <script src="{% static 'bal/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'bal/js/templatemo.js' %}"></script>
    <script src="{% static 'bal/js/custom.js' %}"></script>
    {% endblock js_alani %}

{% block title %}<title>Upload</title>{% endblock title %}



{% block orta_alan %}





    
    <div class="container mt-5 mb-5 ">
    
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <div class="form-group">
              <label for="id_ad">Ürün Adı:</label>
              {{ form.ad }}
            </div>
            
            <div class="form-group">
              <label for="id_aciklama">Ürün Açıklaması:</label>
              {{ form.aciklama }}
            </div>
            
            <div class="form-group">
              <label for="id_fiyat">Ürün Fiyatı:</label>
              {{ form.fiyat }}
            </div>
            
            <div class="form-group">
              <label for="id_resim">Ürün Resmi:</label>
              {{ form.resim }}
            </div>
            <div class="form-group">
              <label for="id_resim">Ürün Aktifmi ?:</label>
              {{ form.isActive }}
            </div>
            
            <button type="submit" class="btn btn-primary">Kaydet</button>
          </form>
          
    
    </div>
    
  


{% endblock orta_alan %}